---
- name: Restart service on Linux hosts
  ansible.builtin.service:
    name: "{{ service_name }}" # Correctly uses generic variable
    state: restarted
  changed_when: true
  # Check for common Linux distributions (Debian, RedHat, Suse are families)
  when: ansible_os_family in ['Debian', 'RedHat', 'Suse']

- name: Restart service on Windows hosts
  ansible.windows.win_service:
    # Uses the generic variable, which will be set correctly for Windows hosts
    name: "{{ service_name }}" 
    state: restarted
  changed_when: true
  # Check for Windows operating system family
  when: ansible_os_family == 'Windows'
