---
- name: Restart service on Linux hosts
  ansible.builtin.service:
    name: "{{ service_name }}" # <-- USE GENERIC VARIABLE
    state: restarted
  changed_when: true
  # Check for common Linux distributions (Debian, RedHat, Suse are families)
  when: ansible_os_family in ['Debian', 'RedHat', 'Suse']

- name: Restart service on Windows hosts
  ansible.windows.win_service:
    # Use the generic variable here too for consistency, 
    # as the service_name can be set to the IIS service name in the outer playbook
    name: "{{ service_name }}" # <-- USE GENERIC VARIABLE
    state: restarted
  changed_when: true
  # Check for Windows operating system family
  when: ansible_os_family == 'Windows'
