---
# Original file: roles/restart_service/tasks/main.yml (with fix)

- name: Force restart {{ service_name | default('rsyslog') }} on Linux hosts
  ansible.builtin.service:
    name: "{{ service_name | default('rsyslog') }}"
    state: restarted
    # FIX: Adding 'force: true' ensures the restart command runs unconditionally
    # and not just as a reload, which should update the 'Active since' time.
    force: true 
  become: true
  changed_when: true
  when: ansible_os_family in ['Debian', 'RedHat', 'Suse']

- name: Wait for 5 seconds after Linux service restart
  ansible.builtin.pause:
    seconds: 5
  when: ansible_os_family in ['Debian', 'RedHat', 'Suse']

- name: Restart service on Windows hosts
  ansible.windows.win_service:
    name: "{{ service_name }}"  
    state: restarted
  changed_when: true
  when: ansible_os_family == 'Windows'

- name: Wait for 5 seconds after Windows service restart
  ansible.builtin.pause:
    seconds: 5
  when: ansible_os_family == 'Windows'
